---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: hyperpilot-operator
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hyperpilot-operator
rules:
  - apiGroups: [""]
    resources:
      - namespaces
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: hyperpilot-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: hyperpilot-operator
  namespace: kube-system

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: hyperpilot-operator
  namespace: kube-system
  labels:
    k8s-app: hyperpilot-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: hyperpilot-operator
    spec:
      serviceAccountName: hyperpilot-operator
      containers:
      - image: hyperpilot/hyperpilot-operator
        name: hyperpilot-operator