apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: hyperpilot-operator
  name: hyperpilot-operator
  namespace: hyperpilot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: hyperpilot-operator
    spec:
      containers:
      - image: ogre0403/hyperpilot-operator:201710201203
        command: ["/hyperpilot-operator"]
        # comment out to monitor all namespace
        # args: ["-namespace", "hyperpilot"]
        imagePullPolicy: Always
        name: hyperpilot-operator
      restartPolicy: Always