apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: hyperpilot-operator
  name: hyperpilot-operator
  namespace: hyperpilot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: hyperpilot-operator
    spec:
      containers:
      - image: hyperpilot/hyperpilot-operator:latest
        command: ["/hyperpilot-operator"]
        imagePullPolicy: Always
        name: hyperpilot-operator
        env:
          - name: HP_POLLANALYZERENABLE
            value: "false"
        ports:
          - containerPort: 8080
            hostPort: 8080
            protocol: TCP
      imagePullSecrets:
        - name: myregistrykey
      restartPolicy: Always