---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxsrv
  name: influxsrv
  namespace: hyperpilot
spec:
  ports:
  - name: port-1
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: port-2
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: influxsrv
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: influxsrv
  name: influxsrv
  namespace: hyperpilot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: influxsrv
    spec:
      hostname: influxsrv
      volumes:
      - hostPath:
          path: "/home/ubuntu/influx_data"
        name: influx-data
      containers:
      - env:
        - name: ADMIN_USER
          value: root
        - name: INFLUXDB_INIT_PWD
          value: default
        - name: INFLUXDB_DATA_INDEX_VERSION
          value: tsi1
        - name: INFLUXDB_DATA_CACHE_SNAPSHOT_WRITE_COLD_DURATION
          value: 1m
        - name: INFLUXDB_DATA_COMPACT_FULL_WRITE_COLD_DURATION
          value: 10m
        image: hyperpilot/influx:1.3.6
        name: influxsrv
        ports:
        - containerPort: 8086
          protocol: TCP
        - containerPort: 8088
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/influxdb"
          name: influx-data
        resources:
          requests:
            cpu: '1'
            memory: 4096Mi
