apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: snap-goddd1
    version: latest
  name: snap-goddd1
spec:
  selector:
    matchLabels:
      app: snap-goddd1
      version: latest
  template:
    metadata:
      labels:
        app: snap-goddd1
        version: latest
    spec:
      containers:
      - image: ogre0403/snap:xenial
        name: snap-goddd1
        command:
        - "/usr/local/bin/run.sh"
        args:
        - https://s3.us-east-2.amazonaws.com/jimmy-hyperpilot/init-resource-worker.json
        ports:
        - containerPort: 8181
          hostPort: 8181
        imagePullPolicy: Always
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: "/var/run"
          name: var-run
        - mountPath: "/var/log"
          name: var-log
        - mountPath: "/sys/fs/cgroup"
          name: cgroup
        - mountPath: "/var/lib/docker"
          name: var-lib-docker
        - mountPath: "/usr/local/bin/docker"
          name: usr-bin-docker
        - mountPath: "/proc_host"
          name: proc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - hostPath:
          path: "/sys/fs/cgroup"
        name: cgroup
      - hostPath:
          path: "/var/lib/docker/"
        name: var-lib-docker
      - hostPath:
          path: "/var/log"
        name: var-log
      - hostPath:
          path: "/var/run"
        name: var-run
      - hostPath:
          path: "/usr/bin/docker"
        name: usr-bin-docker
      - hostPath:
          path: "/proc"
        name: proc
